spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/people
    username: franzoso
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        package-to-scan: com.franzoso.fictional_store.infrastructure.entities
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080